# Generated by Django 5.0.6 on 2024-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('type', models.CharField(choices=[('sexual-abuse', 'Sexual Abuse'), ('forced-labor', 'Forced Labor'), ('domestic-servitude', 'Domestic Servitude'), ('agricultural-labor', 'Agricultural Labor'), ('industrial-work', 'Industrial Work'), ('mining', 'Mining'), ('street-work', 'Street Work'), ('bonded-labor', 'Bonded Labor'), ('child-soldiering', 'Child Soldiering'), ('trafficking', 'Trafficking'), ('informal-sector-work', 'Informal Sector Work'), ('construction-work', 'Construction Work')], default='forced-labor', max_length=100)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('admin_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
